#!bash
rm angular.json
rm package-lock.json
rm package.json
rm src/app/app.component.css
rm src/app/app.component.html
rm src/app/app.component.spec.ts
rm src/app/app.component.ts
rm src/app/app.module.ts
rm src/app/components/page-not-found/page-not-found.component.css
rm src/app/components/page-not-found/page-not-found.component.html
rm src/app/components/page-not-found/page-not-found.component.spec.ts
rm src/app/components/page-not-found/page-not-found.component.ts
rm src/app/components/state/.editorconfig
rm src/app/components/state/state-counties-census-list/state-counties-census-list.component.css
rm src/app/components/state/state-counties-census-list/state-counties-census-list.component.html
rm src/app/components/state/state-counties-census-list/state-counties-census-list.component.spec.ts
rm src/app/components/state/state-counties-census-list/state-counties-census-list.component.ts
rm src/app/components/state/svg-state-counties/svg-state-counties.component.css
rm src/app/components/state/svg-state-counties/svg-state-counties.component.html
rm src/app/components/state/svg-state-counties/svg-state-counties.component.spec.ts
rm src/app/components/state/svg-state-counties/svg-state-counties.component.ts
rm src/app/services/hover.service.spec.ts
rm src/app/services/hover.service.ts
rm src/app/services/state-census-data.service.spec.ts
rm src/app/services/state-census-data.service.ts
rm src/app/test-data/state-census-data.mock.ts
rm src/index.html
rm src/styles.css
rm tsconfig.json_bak
rm src/app/components/us-counties/svg-us-counties/svg-us-counties.component.css
rm src/app/components/us-counties/svg-us-counties/svg-us-counties.component.html
rm src/app/components/us-counties/svg-us-counties/svg-us-counties.component.spec.ts
rm src/app/components/us-counties/svg-us-counties/svg-us-counties.component.ts
rm src/app/components/us-counties/us-counties-census-list/us-counties-census-list.component.css
rm src/app/components/us-counties/us-counties-census-list/us-counties-census-list.component.html
rm src/app/components/us-counties/us-counties-census-list/us-counties-census-list.component.spec.ts
rm src/app/components/us-counties/us-counties-census-list/us-counties-census-list.component.ts
rm src/app/components/us-states/states-census-list/states-census-list.component.css
rm src/app/components/us-states/states-census-list/states-census-list.component.html
rm src/app/components/us-states/states-census-list/states-census-list.component.spec.ts
rm src/app/components/us-states/states-census-list/states-census-list.component.ts
rm src/app/components/us-states/svg-us-states/svg-us-states.component.css
rm src/app/components/us-states/svg-us-states/svg-us-states.component.html
rm src/app/components/us-states/svg-us-states/svg-us-states.component.spec.ts
rm src/app/components/us-states/svg-us-states/svg-us-states.component.ts