DROP TABLE ADDRESS;
CREATE TABLE ADDRESS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ADDR_TYPE INTEGER NOT NULL,
    RANK INTEGER NOT NULL,
    STREET1 VARCHAR (40) ,
    STREET2 VARCHAR (40) ,
    STREET3 VARCHAR (40) ,
    CITY VARCHAR (35) ,
    STATE CHARACTER (2) ,
    ZIP CHARACTER (5) ,
    ZIP_PLUS CHARACTER (4) ,
    EFFDT DATE);
CREATE UNIQUE INDEX ADDRESS ON
    ADDRESS(ID, TYPE, RANK);
COMMIT;