DROP TABLE AGENT;
CREATE TABLE AGENT( 
    ID INTEGER NOT NULL, 
    START_DATE DATE, 
    EXPIRE_DATE DATE, 
    STATUS INT , 
    LICENSE VARCHAR (40) , 
    LICENSE_DT DATE,
    LIC_EX_DT DATE,
    PROPS_LISTED INT,
    PROPS_SOLD INT,
    DESCR TEXT);
CREATE UNIQUE INDEX AGENT ON
    AGENT(ID);
COMMIT;