DROP TABLE AKMLS.ATTRIBUTE;
CREATE TABLE ATTRIBUTE (
    ATTRIBUTE_ID INTEGER NOT NULL AUTO_INCREMENT,
    CLASS_NAME VARCHAR(100) NOT NULL,
    ATTRIBUTE VARCHAR(50),
    RANK INTEGER NOT NULL,
    ATTRIBUTE_NAME VARCHAR (100) ,
    ATTRIBUTE_VALUE TEXT ,
    NOTE TEXT,
    CONSTRAINT ATTRIBUTE_PK PRIMARY KEY ATTRIBUTE_ID);
CREATE UNIQUE INDEX ATTRIBUTE ON
    ATTRIBUTE(CLASS_NAME,ATTRIBUTE, ATTRIBUTE_TYPE, RANK);
COMMIT;