DROP TABLE BLOB_TABLE;
CREATE TABLE BLOB_TABLE ( 
    CLASS       VARCHAR (100) NOT NULL,
    ATTRIBUTE   VARCHAR (50) NOT NULL,
    ID          INTEGER NOT NULL, 
    TYPE        INTEGER NOT NULL, 
    RANK        INTEGER NOT NULL, 
    SIZE        INTEGER NOT NULL,
    NAME        VARCHAR (40) , 
    VALUE       LONGBLOB NOT NULL,
    NOTE        TEXT,
    DT_TM       TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX BLOB_TABLE ON
    BLOB_TABLE(CLASS, ATTRIBUTE, ID, TYPE, RANK, NAME, DT_TM);
COMMIT;