DROP TABLE BROKER;
CREATE TABLE BROKER ( 
    ID INT NOT NULL,
    TYPE INT NOT NULL,
    RANK INT NOT NULL,
    STATUS_CD INT,
    EFFDT DATE NOT NULL,
    ENDDT DATE,
    BROKER_ID VARCHAR (50) NOT NULL, 
    MLS_ID VARCHAR (50),
    COMPANY_NAME  VARCHAR (50) NOT NULL
    );
    
CREATE UNIQUE INDEX BROKER ON
    BROKER(ID, TYPE, RANK);

COMMIT;