DROP TABLE CLOB_TABLE;
CREATE TABLE CLOB_TABLE (
    CLASS       VARCHAR (100) NOT NULL,
    ATTRIBUTE   VARCHAR (50) NOT NULL,
    ID          INTEGER NOT NULL, 
    TYPE        INTEGER NOT NULL, 
    RANK        INTEGER NOT NULL, 
    NAME        VARCHAR (40) , 
    VALUE       TEXT ,
    NOTE        TEXT,
    DT_TM       TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX CLOB_TABLE ON
    CLOB_TABLE(CLASS, ATTRIBUTE, ID, TYPE, RANK, NAME, DT_TM);
COMMIT;