DROP TABLE CONTENT;
CREATE TABLE CONTENT ( 
    ID INT NOT NULL,
    TYPE INT NOT NULL,
    RANK INT NOT NULL,
    URI VARCHAR(100),
    STATUS CHAR(1),
    EFFDT DATE NOT NULL,
    ENDDT DATE,
    MODIFIED DATE,
    MODIFIER INTEGER NOT NULL,
    CLOB_ID INTEGER NOT NULL);
    
CREATE UNIQUE INDEX CONTENT ON
    CONTENT(ID, TYPE, RANK, EFFDT);

COMMIT;
