DROP TABLE EMAIL;
CREATE TABLE EMAIL ( 
    ID INTEGER NOT NULL, 
    TYPE INTEGER NOT NULL, 
    RANK INTEGER NOT NULL, 
    NAME VARCHAR (40) , 
    SERVER VARCHAR (40));
CREATE UNIQUE INDEX EMAIL ON
    EMAIL(ID, TYPE, RANK);
COMMIT;