DROP TABLE FAQ;
CREATE TABLE FAQ ( 
    ID INTEGER NOT NULL, 
    TYPE INTEGER NOT NULL,
    RANK INTEGER NOT NULL,
    QUESTION VARCHAR(255) NOT NULL,
    CLOB_ID INTEGER NOT NULL,
    EFFDT DATE NOT NULL,
    MODIFIER INTEGER NOT NULL);
CREATE UNIQUE INDEX FAQ ON
    FAQ(ID, TYPE, RANK);
COMMIT;