DROP TABLE MESSAGE;
CREATE TABLE MESSAGE ( 
    ID INT NOT NULL,
    TYPE INT NOT NULL,
    RANK INT NOT NULL,
    EFFDT DATE NOT NULL,
    ENDDT DATE,
    TITLE VARCHAR (50) NOT NULL, 
    TEXT  VARCHAR (255) NOT NULL,
    LINK  VARCHAR (100),  
    TARGET VARCHAR (75),
    STATUS VARCHAR (3) NOT NULL);
    
CREATE UNIQUE INDEX MESSAGE ON
    MESSAGE(ID, TYPE, RANK, EFFDT);

COMMIT;
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (1,1,1,'Register', 'Register at Stewart Realty to receive more tools to help you find the real estate you are looking for.','/register.rlt','_self',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (2,1,2,'News Item One', 'News items will appear here.','','',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (3,1,3,'News Item Two', 'Any important news can appear within the applet.','','',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (4,1,4,'New Listings', 'New listings can appear here and link to the page with the listing information.','/newitems.rlt','_self',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (5,1,5,'Important News Items', 'Important news to get out to customers can be here, too','/news.rlt','_self',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (6,3,1,'code','newsscroll.AdvNewsscroll.class','','Class for scroller',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (7,3,2,'width','190','','Scroller witdth',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (8,3,3,'height','175','','Scroller height',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (9,2,1,'info','Applet','','Scroller information',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (10,2,2,'input_text','','from_parameters','Scroller parameter source',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (11,2,3,'text_file','','','Text file name',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (12,2,4,'scroll_mode','scroll','','Scroll mode',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (13,2,5,'bgcolor','EFEFFF','','Background color',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (14,2,6,'title_color','DD9900','','Title color',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (15,2,7,'text_color','888888','','Text color',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (16,2,8,'highlight_title_color','80A0D0','','Hightlight title color',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (17,2,9,'highlight_text_color','50B5F0','','Hightlight text color',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (18,2,10,'title_align','left','','Title alignment',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (19,2,11,'text_align','left','','Text alignment',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (20,2,12,'title_font_type','Helvetica','','Title font type',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (21,2,13,'title_font_size','12','','Title font size (in points)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (22,2,14,'title_font_style','1','','Title font style',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (23,2,15,'text_font_type','Helvetica','','Text font type',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (24,2,16,'text_font_size','11','','Text font size (in points)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (25,2,17,'text_font_style','0','','Text font style',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (26,2,18,'title_underline','no','','Title underline',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (27,2,19,'text_underline','no','','Text underline',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (28,2,20,'scroll_delay','30','','Scrolling delay (miliseconds)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (29,2,21,'pause','3000','','Message pause delay (miliseconds)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (30,2,22,'border_thickness','1','','Border thickness (in pixels)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (31,2,23,'border_color','000099','','Border color (in hex)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (32,2,24,'left_margin','10','','Left margin (in points)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (33,2,25,'top_margin','10','','Top margin (in points)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (34,2,26,'right_margin','5','','Right margin (in points)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (36,2,28,'bottom_margin','10','','Bottom margin (in points)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (37,2,29,'vertical_space','20','','Vertical Space (in points)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (38,2,30,'title_linespace','0','','Title line spacing (in points)',SYSDATE(),NULL,'A');
INSERT INTO MESSAGE (ID, TYPE, RANK, TITLE, TEXT, LINK, TARGET, EFFDT, ENDDT, STATUS) VALUES (39,2,31,'text_linespace','0','','Text line spacing (in points)',SYSDATE(),NULL,'A');