DROP TABLE OPENHOUSE;
CREATE TABLE OPENHOUSE ( 
    ID INT NOT NULL,
    TYPE INT NOT NULL,
    RANK INT NOT NULL,
    STATUS CHAR(1),
    EFFDT DATE NOT NULL,
    STARTDT DATE NOT NULL,
    ENDDT DATE NOT NULL,
    MODIFIED DATE,
    MODIFIER INTEGER NOT NULL,
    CLOB_ID INTEGER NOT NULL);
    
CREATE UNIQUE INDEX OPENHOUSE ON
    OPENHOUSE(ID, TYPE, RANK, EFFDT);

COMMIT;
