DROP TABLE PERSON;
CREATE TABLE PERSON (
    ID INTEGER NOT NULL,
    BIRTHDATE DATE,
    FIRST_NAME VARCHAR (25) ,
    PREFERRED_NAME VARCHAR (25),
    MIDDLE_NAME VARCHAR (25) ,
    LAST_NAME VARCHAR (35) ,
    PASSWORD_HASH VARCHAR (256),
    USER_NAME VARCHAR(100)
    SEX CHARACTER (1) ,
    SSN CHARACTER (9) ,
    LAST_ACCESS DATE,
    USER_NAME VARCHAR (35));
CREATE UNIQUE INDEX PERSON ON
    PERSON(ID);
COMMIT;