DROP TABLE PHOTO;
CREATE TABLE PHOTO ( 
    CLASS       VARCHAR (100) NOT NULL,
    ATTRIBUTE   VARCHAR (50) NOT NULL,
    ID          INTEGER NOT NULL, 
    TYPE        INTEGER NOT NULL, 
    RANK        INTEGER NOT NULL, 
    SIZE        INTEGER NOT NULL,
    CAPTION     VARCHAR (50) ,
    CONTENT     VARCHAR (50) ,
    FILENAME    VARCHAR (100),
    NAME        VARCHAR (40) , 
    WIDTH       INTEGER ,
    HEIGHT      INTEGER ,
    VALUE       LONGBLOB NOT NULL,
    NOTE        TEXT,
    DT_TM       TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX PHOTO ON
    PHOTO(CLASS, ATTRIBUTE, ID, TYPE, RANK);
COMMIT;