DROP TABLE RESOURCE;
CREATE TABLE RESOURCE (
    RESOURCE_ID INTEGER NOT NULL AUTO_INCREMENT,
    TYPE INTEGER NOT NULL,
    RANK INTEGER NOT NULL,
    GROUP_TYPE INTEGER NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    HREF VARCHAR(255) NOT NULL,
    CLOB_ID INTEGER NOT NULL,
    EFFDT DATE NOT NULL,
    MODIFIER INTEGER NOT NULL);
CREATE UNIQUE INDEX RESOURCE ON
    RESOURCE(ID, TYPE, RANK, GROUP_TYPE);
COMMIT;