DROP TABLE ROOM;
CREATE TABLE ROOM ( 
    ID INTEGER NOT NULL, 
    TYPE INTEGER NOT NULL,
    RANK INTEGER NOT NULL,
    SUB_TYPE INTEGER NOT NULL,
    LOCATION DECIMAL (3,1) , 
    LENGTH DECIMAL (8,2) , 
    WIDTH DECIMAL (8,2) , 
    HEIGHT DECIMAL (8,2) , 
    MEASURE_UNITS_ID INTEGER,
    SIZE_ID INTEGER , 
    NOTE VARCHAR (500));
CREATE UNIQUE INDEX ROOM ON
    ROOM(ID, RANK);
COMMIT;