DROP TABLE SEARCH;
CREATE TABLE SEARCH( 
    ID INTEGER NOT NULL, 
    SEARCH_ID INTEGER NOT NULL, 
    TABLE_NAME VARCHAR(40),
    FIELD_NAME VARCHAR(40), 
    VALUE VARCHAR(40), 
    COMPARE VARCHAR (10) , 
    METHOD VARCHAR (15),
    MULTI_OP VARCHAR (15),
    MULTI_FIELD CHAR (1),
    STATUS CHAR (1),
    EFFDT DATE);
CREATE UNIQUE INDEX SEARCH ON
    SEARCH(ID, SEARCH_ID, TABLE_NAME, FIELD_NAME, VALUE);
COMMIT;