DROP TABLE SECURITY;
CREATE TABLE SECURITY ( 
    ID INTEGER NOT NULL, 
    SECURITY_ID INTEGER NOT NULL, 
    EFFDT DATE NOT NULL );
DROP INDEX SECURITY;
CREATE UNIQUE INDEX SECURITY ON
    SECURITY(ID, SECURITY_ID, EFFDT);
COMMIT;