DROP TABLE TRANS_LOG;
CREATE TABLE TRANS_LOG ( 
    DTTM_STAMP TIMESTAMP NOT NULL, 
    EVENT VARCHAR (10)  NOT NULL, 
    ID INTEGER NOT NULL, 
    SESSION_ID VARCHAR (50),
    SRC VARCHAR (15)  NOT NULL );
COMMIT;